### ISSUE TITLE
Add your name to the CONTRIBUTORS.md file

### ISSUE THREAD

**Issue by Architgupta001** [Architgupta001/Hacktoberfest-2021#1]
Add your name to the CONTRIBUTORS.md file using following model
Name: [YOUR NAME](Github Link)
Place: city you belong to
About: Short Intro

**Comment by palash9561** [comment]
Hey can you assign this to me and also could you brief on that do i have to make file as well

**Comment by Im-Abhi** [comment]
Hey, Can I work on this issue.

**Comment by Architgupta001** [comment]
yes sure
