### ISSUE TITLE
Word Break

### ISSUE THREAD

**Issue by vishakha-managoli** [Architgupta001/Hacktoberfest-2021#258]
Given a string s and a dictionary of strings wordDict, return true if s can be segmented into a space-separated sequence of one or more dictionary words.

Note that the same word in the dictionary may be reused multiple times in the segmentation.
Example-
Input: s = "applepenapple", wordDict = ["apple","pen"]
Output: true

**Comment by Architgupta001** [comment]
go for it @vishakha-managoli
